# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatRPC.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ChatRPC.proto',
  package='grpc',
  syntax='proto3',
  serialized_pb=_b('\n\rChatRPC.proto\x12\x04grpc\"\x07\n\x05Vacio\"J\n\x07Mensaje\x12\x0e\n\x06Nombre\x18\x01 \x01(\t\x12\x10\n\x08Receptor\x18\x02 \x01(\t\x12\r\n\x05Texto\x18\x03 \x01(\t\x12\x0e\n\x06Tiempo\x18\x04 \x01(\t2\xc1\x01\n\x0c\x43hatServidor\x12*\n\nChatStream\x12\x0b.grpc.Vacio\x1a\r.grpc.Mensaje0\x01\x12+\n\rEnviarMensaje\x12\r.grpc.Mensaje\x1a\x0b.grpc.Vacio\x12+\n\rHistorialChat\x12\r.grpc.Mensaje\x1a\x0b.grpc.Vacio\x12+\n\rListaClientes\x12\r.grpc.Mensaje\x1a\x0b.grpc.Vaciob\x06proto3')
)




_VACIO = _descriptor.Descriptor(
  name='Vacio',
  full_name='grpc.Vacio',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=30,
)


_MENSAJE = _descriptor.Descriptor(
  name='Mensaje',
  full_name='grpc.Mensaje',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Nombre', full_name='grpc.Mensaje.Nombre', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Receptor', full_name='grpc.Mensaje.Receptor', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Texto', full_name='grpc.Mensaje.Texto', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Tiempo', full_name='grpc.Mensaje.Tiempo', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['Vacio'] = _VACIO
DESCRIPTOR.message_types_by_name['Mensaje'] = _MENSAJE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vacio = _reflection.GeneratedProtocolMessageType('Vacio', (_message.Message,), dict(
  DESCRIPTOR = _VACIO,
  __module__ = 'ChatRPC_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Vacio)
  ))
_sym_db.RegisterMessage(Vacio)

Mensaje = _reflection.GeneratedProtocolMessageType('Mensaje', (_message.Message,), dict(
  DESCRIPTOR = _MENSAJE,
  __module__ = 'ChatRPC_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Mensaje)
  ))
_sym_db.RegisterMessage(Mensaje)



_CHATSERVIDOR = _descriptor.ServiceDescriptor(
  name='ChatServidor',
  full_name='grpc.ChatServidor',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=109,
  serialized_end=302,
  methods=[
  _descriptor.MethodDescriptor(
    name='ChatStream',
    full_name='grpc.ChatServidor.ChatStream',
    index=0,
    containing_service=None,
    input_type=_VACIO,
    output_type=_MENSAJE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='EnviarMensaje',
    full_name='grpc.ChatServidor.EnviarMensaje',
    index=1,
    containing_service=None,
    input_type=_MENSAJE,
    output_type=_VACIO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='HistorialChat',
    full_name='grpc.ChatServidor.HistorialChat',
    index=2,
    containing_service=None,
    input_type=_MENSAJE,
    output_type=_VACIO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListaClientes',
    full_name='grpc.ChatServidor.ListaClientes',
    index=3,
    containing_service=None,
    input_type=_MENSAJE,
    output_type=_VACIO,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATSERVIDOR)

DESCRIPTOR.services_by_name['ChatServidor'] = _CHATSERVIDOR

# @@protoc_insertion_point(module_scope)
